# Copyright 2016 WebAssembly Community Group participants
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Common definitions of spec tests.
#
# To test run:
#
#    make
#
# To update spec tests run:
#
#    make -f Makefile.update

ifdef DEBUG
  ifdef RELEASE
    ifeq ($(DEBUG), 0)
      ifneq ($(RELEASE), 0)
	RELEASE = 1
      else
        $(error Cant specify both DEBUG and RELEASE)
      endif
    else ifneq ($(RELEASE), 0)
      $(error Cant specify both DEBUG and RELEASE)
    endif
  else ifeq ($(DEBUG), 0)
    RELEASE = 1
  else
    RELEASE = 0
  endif
else ifndef RELEASE
  RELEASE = 0
endif

BUILDDIR = ../../build

SEXP_SRCDIR = ../../src/sexp
SEXP_DEFAULTS = $(SEXP_SRCDIR)/defaults.df

ifeq ($(RELEASE), 0)
  BUILD_RELEASE_DIR = $(BUILDDIR)/debug
else
  BUILD_RELEASE_DIR = $(BUILDDIR)/release
endif

EXEC_DIR = $(BUILD_RELEASE_DIR)/bin
TEST_DIR = $(BUILD_RELEASE_DIR)/test

LOCAL_SEXPS_DIR = spec

# Note: the following spec test are not included because they do not generate a
# valid wasm file.
#	br_table.wast \
#	func-local-after-body.fail.wast \
#	func-local-before-param.fail.wast \
#	func-local-before-result.fail.wast \
#	func-param-after-body.fail.wast \
#	func-result-after-body.fail.wast \
#	func-result-before-param.fail.wast \
#	if_label_scope.fail.wast \
#	of_string-overflow-hex-u32.fail.wast \
#	of_string-overflow-hex-u64.fail.wast \
#	of_string-overflow-s32.fail.wast \
#	of_string-overflow-s64.fail.wast \
#	of_string-overflow-u32.fail.wast \
#	of_string-overflow-u64.fail.wast \

SEXPS = address.wast \
	binary.wast \
	block.wast \
	break-drop.wast \
	br_if.wast \
	br.wast \
	call_indirect.wast \
	call.wast \
	comments.wast \
	conversions.wast \
	endianness.wast \
	exports.wast \
	f32_cmp.wast \
	f32.wast \
	f64_cmp.wast \
	f64.wast \
	fac.wast \
	float_exprs.wast \
	float_literals.wast \
	float_memory.wast \
	float_misc.wast \
	forward.wast \
	func_ptrs.wast \
	func.wast \
	get_local.wast \
	i32.wast \
	i64.wast \
	imports.wast \
	int_exprs.wast \
	int_literals.wast \
	labels.wast \
	left-to-right.wast \
	loop.wast \
	memory_redundancy.wast \
	memory_trap.wast \
	memory.wast \
	names.wast \
	nan-propagation.wast \
	nop.wast \
	resizing.wast \
	return.wast \
	select.wast \
	set_local.wast \
	start.wast \
	store_retval.wast \
	switch.wast \
	traps.wast \
	typecheck.wast \
	unreachable.wast

LOCAL_TESTS=$(patsubst %.wast, $(LOCAL_SEXPS_DIR)/%.test, $(SEXPS))

$(info -----------------------------------------------)
$(info SEXPS = $(SEXPS))
$(info -----------------------------------------------)
