# Copyright 2016 WebAssembly Community Group participants
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copies test wast file (WASM s-expressions) to this directory, and then
# converts them to binary form. This allows us to easily build test cases.
#
# To update spec tests run:
#
#     make -f Makefile.update
#
# To update other test files, use form:
#
#    make -f Makefile.update FILE
#
# where FILE is the name of the file.
#
# Note: The make file has been separated from the main make file (Makefile)
# because it has requirements on other WebAssembly projects. In particular, the
# following projects must be downloaded:
#
#   sexpr-wasm-prototype
#   spec
#
# In addition, you need to build the following projects:
#
#   sexpr-wasm-prototype.

include Makefile.common

SEXP_WASM_DIR = $(PARENT_DIR)/../sexpr-wasm-prototype

SPEC_SEXPS_DIR = $(PARENT_DIR)/../spec/ml-proto/test

SPEC_SEXPS_SRCS=$(patsubst %.wast, $(SPEC_SEXPS_DIR)/%.wast, $(SEXPS))
LOCAL_SEXPS_SRCS=$(patsubst %.wast, $(LOCAL_SEXPS_DIR)/%.wast, $(SEXPS))
LOCAL_SEXPS_BINS=$(patsubst %.wast, $(LOCAL_SEXPS_DIR)/%.wasm, $(SEXPS))

SEXP_DEFAULT_TEST_SRCS = $(patsubst %.df, $(TEST_SRCS_DIR)/%.df, $(SEXP_DEFAULT_DFS))
SEXP_DEFAULT_WASMS = $(patsubst %.df, $(TEST_SRCS_DIR)/%.wasm, $(SEXP_DEFAULT_DFS))
SEXP_DEFAULT_WASMS_W = $(patsubst %.df, $(TEST_SRCS_DIR)/%.wasm-w, $(SEXP_DEFAULT_DFS))

$(info TEST_SRCS_DIR = $(TEST_SRCS_DIR))
$(info SEXP_DEFAULT_WASMS = $(SEXP_DEFAULT_WASMS))

$(info -----------------------------------------------)
$(info ***NOTE*** Expect error messages while generating wasm files.)
$(info -----------------------------------------------)

# NOTE: update will have LOTS of error messages, but they can be ignored.
spec: clean_binaries $(LOCAL_SEXPS_SRCS) $(LOCAL_SEXPS_BINS)

$(SEXP_DEFAULT_WASMS): %.wasm: $(TEST_SRCS_DIR)/%.df
	$(EXEC_DIR)/decompsexp-wasm -m -i $< -o $@

$(SEXP_DEFAULT_WASMS_W): %.wasm-w: $(TEST_SRCS_DIR)/%.df
	$(EXEC_DIR)/decompsexp-wasm -i $< -o $@

$(SEXP_DEFAULT_TEST_SRCS): $(TEST_SRCS_DIR)/%.df: $(SEXP_SRCDIR)/%.df
	$(TEST_DIR)/TestParser -w $< > $@


ExprRedirects.df-out:
	$(TEST_DIR)/TestParser -w ExprRedirects.df > ExprRedirects.df-out

.PHONY: ExprRedirects.df-out

clean: clean_binaries
	rm -rf $(LOCAL_SEXPS_DIR)

.PHONY: clean

clean_binaries:
	rm -rf $(LOCAL_SEXPS_BINS)

$(LOCAL_SEXPS_SRCS): | $(LOCAL_SEXPS_DIR)

$(LOCAL_SEXPS_BINS): | $(LOCAL_SEXPS_DIR)

$(LOCAL_TESTS): | $(LOCAL_SEXPS_DIR)

$(LOCAL_SEXPS_DIR):
	mkdir -p $@

$(LOCAL_SEXPS_SRCS): $(LOCAL_SEXPS_DIR)/%.wast: $(SPEC_SEXPS_DIR)/%.wast
	cp $< $@

# NOTE: sexpr-wasm will have lots of error messages, but they do not block
# building the corresponding wasm files.
$(LOCAL_SEXPS_BINS): $(LOCAL_SEXPS_DIR)/%.wasm: $(LOCAL_SEXPS_DIR)/%.wast
	$(SEXP_WASM_DIR)/out/sexpr-wasm $< -o $@

